"use client";

import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export async function exportToPDF(
  element: HTMLElement,
  filename: string,
  title: string,
  subtitle?: string
) {
  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: "#060E1A",
    logging: false,
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;

  // Header
  pdf.setFillColor(6, 14, 26);
  pdf.rect(0, 0, pageWidth, 25, "F");

  pdf.setTextColor(26, 184, 158);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("eazyCare.Ai", margin, 12);

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  pdf.text(title, margin, 19);

  if (subtitle) {
    pdf.setFontSize(9);
    pdf.setTextColor(200, 200, 200);
    pdf.text(subtitle, margin, 24);
  }

  // Image
  const imgWidth = pageWidth - margin * 2;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  let position = 30;

  pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);

  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by eazyCare.Ai | ${new Date().toLocaleDateString()} | Page ${i} of ${totalPages}`,
      margin,
      pageHeight - 5
    );
    pdf.text(
      "Confidential — Internal Use Only",
      pageWidth - margin,
      pageHeight - 5,
      { align: "right" }
    );
  }

  pdf.save(filename);
}
